"""initial models

Revision ID: d65b01c7259d
Revises: 
Create Date: 2026-09-05 18:56:47.342812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd65b01c7259d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mines_id'), 'mines', ['id'], unique=False)
    op.create_table('prospectivity_zones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('geometry', sa.String(), nullable=False),
    sa.Column('prospectivity_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reserve_min', sa.Float(), nullable=True),
    sa.Column('reserve_max', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mine_id', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('planned_tonnes', sa.Float(), nullable=False),
    sa.Column('forecast_tonnes', sa.Float(), nullable=False),
    sa.Column('shortfall_pct', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mine_id', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('planned_tonnes', sa.Float(), nullable=False),
    sa.Column('actual_tonnes', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mine_id', sa.String(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('primary_cause', sa.String(), nullable=False),
    sa.Column('recommendation_text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_factors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mine_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weight_pct', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_factors')
    op.drop_table('recommendations')
    op.drop_table('production_records')
    op.drop_table('forecasts')
    op.drop_table('prospectivity_zones')
    op.drop_index(op.f('ix_mines_id'), table_name='mines')
    op.drop_table('mines')
    # ### end Alembic commands ###
